// Generated by precompileHTML
//
//
// #####################
// ##  DO NOT MODIFY  ##
// #####################
//
#pragma once
#include "../web-server/Part.h"


class PartApp :public Part
{
public:
	static const int content = 1;
	PartApp()
	{
		tokenList.push_back({ "<!DOCTYPE html>",Token::Type::html,0 });
		tokenList.push_back({ {65,66,67},Token::Type::html,0 });
		tokenList.push_back({ "<html lang=\"en\">",Token::Type::html ,0 });
		tokenList.push_back({ "<head><link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\"><link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap.css\" > ",Token::Type::html ,0 });
		tokenList.push_back({ "<meta charset=\"UTF - 8\">",Token::Type::html,0 });
		tokenList.push_back({ "<title>Testing</title>",Token::Type::html,0 });
		tokenList.push_back({ "</head><body><h1>Headline from App.html</h1>",Token::Type::html ,0 });
		tokenList.push_back({ "content",Token::Type::part,1 });
		tokenList.push_back({ "</body></html> ",Token::Type::html,0 });
	}
};

