// Generated by precompileHTML
//
//
// #####################
// ##  DO NOT MODIFY  ##
// #####################
//

#pragma once
#include "../../web-server/Part.h"

	class Partone :public Part
	{
	public:

		Partone()
		{
			tokenList.push_back({ "<p>First Content</p>",Token::Type::html,0 });
		}

	private:

	};
